services:
    mysql:
        image: mysql:8.0
        container_name: indrasari_car_rental_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "[PASSWORD]"
            MYSQL_DATABASE: db_indrasari_car_rental
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
